sitio/urls.py
from django.contrib import admin
from django.urls import path, include
from aplicacion import views as views
#PARA IMAGEN
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/',include('django.contrib.auth.urls')),
    
    #Páginas principales
    path('', views.index, name='index'),
    path('tienda/', views.tienda, name='tienda'),
    path('pagina_general_libro/<isbn>/', views.gral_libro, name='libro'),
    path('inf_pago/', views.inf_pago, name='inf_pago'),
    #carrito
    path('pagina_carrito_general/', views.carrito, name='carrito'),
    path('agregar_al_carrito/<isbn>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('eliminar_del_carrito/<int:carrito_id>/', views.eliminar_del_carrito, name='eliminar_del_carrito'),
    path('pagina_domicilio_y_pagar/', views.domicilio, name='domicilio'),

    #Páginas usuario
    path('user/', views.usuario, name='usuario'),

    #Paginas inicio de sesión
    path('Cambio_de_contraseña/', views.c_contra, name='c_contra'),
    path('Inicio_secion/', views.ini_sesion, name='ini_sesion'),
    path('salir/',views.salir,name='salir'),
    path('Registro_usuario/', views.reg_user, name='reg_user'),

    #Páginas categorias de libros
    path('biografia/', views.biografia, name='biografia'),
    path('historia/', views.historia, name='historia'),
    path('misterio/', views.misterio, name='misterio'),
    path('sci_fi/', views.sci_fi, name='sci_fi'),
    path('terror/', views.terror, name='terror'),

    #Admin
    path('agregar/', views.agregar, name='agregar'),
    path('buscar/', views.buscar, name='buscar'),
    path('crear/', views.crear, name='crear'),
    path('eliminar/<isbn>/', views.eliminar, name='eliminar'),
    path('modificar/<isbn>/', views.modificar, name='modificar'),
    path('pedidos/', views.pedidos, name='pedidos'),
    path('usuario_gnral/', views.usuario_gnral, name='usuario_gnral'),
    path('usuarios/', views.usuarios, name='usuarios'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicacion/models.py
from django.db import models
from .listas import TIPO_GENERO,SUBTIPO_GENERO,TIPO_ESTADO
# Create your models here.
from django.core.validators import MinValueValidator
from datetime import date
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.exceptions import ValidationError


# Create your models here.
class Libro(models.Model):
    #no se si dejar el isbn como clave primaria o ponerle un id para diferenciarlos
    isbn=models.CharField(max_length=13, primary_key=True, null=False)
    nombre=models.CharField(max_length=50, null=False)
    nombre_autor=models.CharField(max_length=50, null=False, default='no posee autor')#falta el autor en el html
    foto=models.ImageField("Imagen",upload_to='libros',null=True)
    precio=models.IntegerField(validators=[MinValueValidator(0)])
    best_seler= models.BooleanField(default=False)#Falta agregar en el html el boton deslizante de si o no en el html

    tipo=models.CharField(max_length=30, choices=TIPO_GENERO, default='Sin tipo')
    subtipo=models.CharField(max_length=40, choices=SUBTIPO_GENERO, default='Sin subtipo')
    def __str__(self):
        return self.nombre
        #return f"nombre {self.nombre} precio: {self.precio} "
    
class Usuario(models.Model):
    id=models.AutoField(primary_key=True)
    direccion=models.CharField(max_length=60, null=False, default='no hay direccion')#poner un minimo de 3 como en el js
    correo=models.CharField(max_length=100, null=False)
    contraseña=models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.nombre


class Carrito(models.Model):
    comprador_carrito = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    libro = models.ForeignKey(Libro, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)  # Asegúrate de tener un valor por defecto

    def __str__(self):
        return f"{self.comprador_carrito.correo} - {self.libro.nombre} - {self.cantidad}"

class Pedido(models.Model):
    numero_pedido = models.AutoField(primary_key=True)
    comprador_pedido = models.ForeignKey(Usuario, on_delete=models.CASCADE, default=1)  # Aquí el 1 sería el ID de un usuario predeterminado o según tu lógica
    total = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_pedido = models.DateField(default=date.today)
    estado_pedido = models.CharField(max_length=40, choices=TIPO_ESTADO, default='En proceso')

    def __str__(self):
        return f"Pedido #{self.numero_pedido} - {self.comprador_pedido.correo}"


class DetallePedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Libro, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.pedido} - {self.producto} - {self.cantidad}"
    
#no se si dejar la entidad oferta, pero como esta en la pagina, los determinados libros con descuento estan separados de los normales en la pagina general
#class libro_oferta(models.Model):
    # d#escuento = models.DecimalField(max_digits=10, decimal_places=2)
    # def __str__(self):
    #    return self.libro
    


#se reutiliza el detalle del pedido para TENER LA INFORMACION DEL HISTORICO DE LAS COMPRAS QUE VE EL ADMIN Y EL MISMO USUARIO
#o ocupar lo que me ayudo chat gpt y hacerlo de la forma de abajo :v



    

#Hacer el boton de tipo targeta reciclando el boton del domicilio para los 4 tipos de targeta de forma manual tipo boton deslizable

#tambien falta hacer los def para que las clases devuelvan la infrormacion, pero al final XD

#Debemos realizar el logo de nuevo que contenga: .¿(despues XD)

aplicacion/forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
#from .models import Product
from django import forms
from .models import Libro
from django.http import JsonResponse
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, Field

"""
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'stock', 'description', 'image']

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Row(
                Column('name', css_class='form-group mb-0 col-md-6'),
                Column('price', css_class='form-group mb-0 col-md-6'),
                css_class='form-row'
            ),
            Row(
                Column('stock', css_class='form-group mb-0 col-md-6'),
                Column('description', css_class='form-group mb-0 col-md-6'),
                css_class='form-row'
            ),
            Row(
                Column('image', css_class='form-group mb-0 col-md-6'),
                css_class='form-row'
            ),
            Submit('submit', 'Agregar Producto', css_class='btn btn-primary')
        )
        # Add custom classes to fields
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})
"""

#def index(request):
 #   products = Product.objects.all()
 #   return render(request, 'pages/index.html', {'products': products})
"""""
def delete_product(request, id):
    if request.method == 'POST':
        product = get_object_or_404(Product, pk=id)
        product.delete()
        return redirect('index')
    return JsonResponse({'error': 'Invalid request method'}, status=400)
    
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = ProductForm()
    
    products = Product.objects.all()
    return render(request, 'pages/index.html', {'products': products, 'form': form})
"""
class LoginForm(forms.Form):
    username = forms.CharField(label="Nombre de usuario")
    password = forms.CharField(label="Contraseña", widget=forms.PasswordInput)

class Libro_agregarForm(forms.ModelForm):
    class Meta:
        model = Libro
        fields = ['isbn', 'nombre','nombre_autor','tipo', 'precio','subtipo', 'best_seler','foto']

aplicacion/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Carrito, Libro, Usuario
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import LoginForm, Libro_agregarForm, LibroForm, LibroFormMod
from django.contrib.auth import logout
from django.contrib.auth.models import User
# Vistas principales 
def index(request):

    libro = Libro.objects.all()
    data = {
        'libro': libro
    }
    return render(request, 'aplicacion/index.html', data)

def tienda(request):
    
    libro = Libro.objects.all()
    data = {
        'libro': libro
    }
    return render(request, 'aplicacion/tienda.html', data)

def gral_libro(request, isbn):
    general = get_object_or_404(Libro, isbn=isbn)
    libro = Libro.objects.all()
    data = {
        'libro': libro,
        'general': general,
    }
    return render(request, 'aplicacion/pagina_general_libro.html', data)

def inf_pago(request):
    return render(request, 'aplicacion/inf_pago.html')
@login_required
def carrito(request):
    usuario = request.user.id
    carrito_items = Carrito.objects.filter(comprador_carrito=usuario)
    total = sum(item.libro.precio * item.cantidad for item in carrito_items)
    return render(request, 'aplicacion/pagina_carrito_general.html', {'carrito_items': carrito_items, 'total': total})

@login_required
def agregar_al_carrito(request):
    if request.method == 'POST':
        usuario = request.user
        isbn = request.POST.get('isbn')  # Obtener el ISBN del formulario POST
        libro = get_object_or_404(Libro, isbn=isbn)

        # Verificar si ya existe el libro en el carrito del usuario
        carrito, created = Carrito.objects.get_or_create(comprador_carrito=usuario, libro=libro)

        if not created:
            carrito.cantidad += 1
        else:
            carrito.cantidad = 1
        
        carrito.save()  # Guardar el carrito en ambos casos

        return redirect('carrito')  # Redirigir al carrito después de agregar el libro
    else:
        return redirect('inicio')  # Redirigir a la página de inicio si no es una solicitud POST válida
    
def eliminar_del_carrito(request, carrito_id):
    carrito = get_object_or_404(Carrito, id=carrito_id)
    carrito.delete()
    return redirect('carrito') 

def domicilio(request):
    return render(request, 'aplicacion/pagina_domicilio_y_pagar.html')

#Vistas de usuario
def usuario(request):
    return render(request, 'aplicacion/usuario/user.html')

#Vistas de sesión
def c_contra(request):
    return render(request, 'aplicacion/paginas_inicio_secion/Cambio_de_contraseña.html')

def ini_sesion(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                # Redirigir a una página después del inicio de sesión exitoso
                return redirect('index')  # Ajusta 'dashboard' según tu configuración de URLs
            else:
                messages.error(request, 'Nombre de usuario o contraseña incorrectos.')
    else:
        form = LoginForm()
    return render(request, 'aplicacion/paginas_inicio_secion/Inicio_secion.html', {'form': form})

def salir(request):
    logout(request)
    messages.info(request,'Sesión Cerrada')
    return redirect(to="index")

def reg_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'¡Cuenta creada para {username}!')
            return redirect('ini_sesion')
    else:
        form = UserCreationForm()
    return render(request, 'aplicacion/paginas_inicio_secion/Registro_usuario.html', {'form': form})

# Vistas de las categorías de libros

#Vistas de las categorias de libros
def biografia(request):
    libro = Libro.objects.all()
    data = {
        'libro': libro
    }
    return render(request, 'aplicacion/libros_categorias/biografia.html', data)

def historia(request):
    libro = Libro.objects.all()
    data = {
        'libro': libro
    }
    return render(request, 'aplicacion/libros_categorias/historia.html', data)

def misterio(request):
    libro = Libro.objects.all()
    data = {
        'libro': libro
    }
    return render(request, 'aplicacion/libros_categorias/misterio.html', data)

def sci_fi(request):
    libro = Libro.objects.all()
    data = {
        'libro': libro
    }
    return render(request, 'aplicacion/libros_categorias/sci_fi.html', data)

def terror(request):
    libro = Libro.objects.all()
    data = {
        'libro': libro
    }
    return render(request, 'aplicacion/libros_categorias/terror.html', data)

#Vistas admin
def agregar(request):
    exito = False  # Variable para controlar si mostrar el mensaje de éxito
    
    if request.method == 'POST':
        form = LibroForm(request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            exito = True  # Cambia el estado de éxito a True después de guardar el libro correctamente
            # Puedes agregar más lógica aquí si lo necesitas antes de redirigir o renderizar nuevamente
    else:
        form = LibroForm()

    data = {
        'form': form,
        'exito': exito,  # Pasar la variable exito al contexto de la plantilla
    }
    return render(request, 'aplicacion/imenu-w/agregar_producto.html', data)

def buscar(request):
    libros = Libro.objects.all()

    data={
        'libros': libros
    }
    return render(request, 'aplicacion/imenu-w/buscar_producto.html', data)

def crear(request):
    return render(request, 'aplicacion/imenu-w/crear_cuenta.html')

def eliminar(request, isbn):
    libro = get_object_or_404(Libro, isbn=isbn)
    libro.delete()
    return redirect(to="buscar")

def modificar(request, isbn):
    libro = get_object_or_404(Libro, isbn=isbn)

    if request.method == 'POST':
        formulario = LibroFormMod(request.POST, request.FILES, instance=libro)
        if formulario.is_valid():
            formulario.save()
            return redirect('buscar')
    else:
        formulario = LibroFormMod(instance=libro)

    # No permitir modificar el campo isbn en el formulario
    formulario.fields['isbn'].disabled = True

    data = {
        'form': formulario
    }
    return render(request, 'aplicacion/imenu-w/modificar_producto.html', data)

def pedidos(request):
    return render(request, 'aplicacion/imenu-w/pedidos.html')

def usuario_gnral(request):
    return render(request, 'aplicacion/imenu-w/usuario_gnral.html')

def usuarios(request):
    return render(request, 'aplicacion/imenu-w/usuarios.html')

aplicacion/templates/aplicacion/usuario/user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link href="
https://cdn.jsdelivr.net/npm/izitoast@1.4.0/dist/css/iziToast.min.css
" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'aplicacion/css/libs.css' %}">
</head>

<body style="padding-top: 50px;">
    <!-- Navbar (sit on top) -->
    <div class="w3-top">
        <div class="w3-bar w3-white w3-card" id="myNavbar">
            <a href="{% url 'index' %}" class="w3-bar-item w3-button w3-wide efect">Entre Verbos</a>
            <!-- Right-sided navbar links -->
            <div class="w3-right w3-hide-small l-efect">
                <a href="{% url 'index' %}" class="w3-bar-item w3-button">Inicio</a>
                <a href="{% url 'tienda' %}" class="w3-bar-item w3-button"><i class="fa fa-th"></i> Tienda</a>
        
                {% if user.is_authenticated %}
                <a href="{% url 'carrito' %}" class="w3-bar-item w3-button"><i class="fa fa-usd"></i>
                    Carrito</a>
                <a href="{% url 'usuario' %}" class="w3-bar-item w3-button"><i class="fa fa-user"></i> Usuario: {{user.username}}</a>
                <a href="#" class="w3-bar-item w3-button" onclick="cerrarSesion('/salir/')">
                    <i class="fa fa-envelope"></i> Cerrar sesión
                </a>
                {% else %}
                <a href="{% url 'ini_sesion' %}" class="w3-bar-item w3-button"><i
                    class="fa fa-envelope"></i> Iniciar Sesión</a>
                {% endif %}
            </div>
            <!-- Hide right-floated links on small screens and replace them with a menu icon -->

            <a href="javascript:void(0)" class="w3-bar-item w3-button w3-right w3-hide-large w3-hide-medium"
                onclick="w3_open()">
                <i class="fa fa-bars"></i>
            </a>
        </div>
    </div>

    <!-- Sidebar on small screens when clicking the menu icon -->
    <nav class="w3-sidebar w3-bar-block w3-black w3-card w3-animate-left w3-hide-medium w3-hide-large"
        style="display:none" id="mySidebar">
        <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button w3-large w3-padding-16">Cerrar
            ×</a>
        <a href="{% url 'index' %}" onclick="w3_close()" class="w3-bar-item w3-button">Inicio</a>
        <a href="{% url 'tienda' %}" onclick="w3_close()" class="w3-bar-item w3-button">Tienda</a>
        <a href="{% url 'carrito' %}" onclick="w3_close()" class="w3-bar-item w3-button">Carrito</a>
        <a href="{% url 'ini_sesion' %}" onclick="w3_close()" class="w3-bar-item w3-button">Iniciar Sesión</a>
        <a href="{% url 'usuario' %}" onclick="w3_close()" class="w3-bar-item w3-button">Usuario</a>
    </nav>


    <div class="row mt-5 p-4">
        <div class="col-4 card" style="width:400px">
            <img class="card-img-top" src="{% static 'aplicacion/img/user.jpeg' %}" alt="Card image">
            <div class="card-body text-center">
                <h4 class="card-title">Jhon Doe</h4>
                <p class="card-text">jhondoe5@gmail.com</p>
                <a href="{% url 'c_contra' %}" class="btn btn-primary">Modificar
                    sesión</a>
            </div>
            <div class="container admin">
                {% if user.is_authenticated %}
                    {% if perms.aplicacion.delete_libro %}
                        <a href="{% url 'agregar' %}">Ingreso Admin</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        <div class="col-8">
            <table class="table mt-5">
                <thead class="table-dark">
                    <tr>
                        <th>Libro</th>
                        <th>Autor</th>
                        <th>Precio</th>
                        <th>Estado</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>El Hobbit</td>
                        <td>J.R.R. Tolkien</td>
                        <td>13.900</td>
                        <td>Entregado</td>
                        <td><a href="{% url 'libro' %}" class="btn btn-primary">Ver compra</a></td>
                    </tr>
                    <tr>
                        <td>Metro</td>
                        <td>Dmitry Glukhovsky</td>
                        <td>14.9000</td>
                        <td>Entregado</td>
                        <td><a href="{% url 'libro' %}" class="btn btn-primary">Ver compra</a></td>
                    </tr>
                    <tr>
                        <td>Holly</td>
                        <td>Stephen King</td>
                        <td>12.900</td>
                        <td>En proceso</td>
                        <td><a href="{% url 'libro' %}" class="btn btn-primary">Ver compra</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <script src="../../js/menus.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>
    <script src="{% static 'aplicacion/js/messages.js' %}"></script>
</body>

</html>